ARG TAG=latest

FROM opensearchproject/opensearch:${TAG}

ARG UID
ARG GID

USER root

RUN chown -R ${UID}:${GID} /usr/share/opensearch /usr/share/opensearch/logs /usr/share/opensearch/config

USER ${UID}:${GID}
