#!/bin/bash

export OT_RELEASE="25.03-testrun-3"

export OT_DATA_URL="gs://open-targets-pre-data-releases/$OT_RELEASE/disk_images"

export OT_OPENSEARCH_TAG="2.19.1"
export OT_CLICKHOUSE_TAG="23.3.1.2823"
export OT_API_TAG="25.0.0-alpha.14"
export OT_OPENAI_TAG="0.0.10"
export OT_WEBAPP_IMAGE="ghcr.io/javfg/ot-ui-apps/ot-ui-apps"
export OT_WEBAPP_TAG="0.11.11"

# if set to `true`, disable cache and set log level to debug
export OT_DEBUG=true

# if set to `true`, expose the services to the internet
export OT_EXPOSE=true
